DROP TABLE IF EXISTS paises;
CREATE TABLE paises (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nombre VARCHAR(100) NOT NULL,
                        codigo_iso CHAR(3)  NOT NULL,
                        capital VARCHAR(100) NOT NULL,
                        poblacion BIGINT NOT NULL,
                        superficie_km2 DOUBLE NOT NULL,
                        moneda VARCHAR(50) NOT NULL,
                        idioma_principal VARCHAR(50) NOT NULL,
                        continente VARCHAR(30) NOT NULL
);

INSERT INTO paises (nombre, codigo_iso, capital, poblacion, superficie_km2, moneda, idioma_principal, continente)
VALUES ('España', 'ESP', 'Madrid', 48000000, 505990, 'Euro (EUR)', 'Español', 'Europa');
INSERT INTO paises (nombre, codigo_iso, capital, poblacion, superficie_km2, moneda, idioma_principal, continente)
VALUES ('Francia', 'FRA', 'París', 67000000, 551695, 'Euro (EUR)', 'Francés', 'Europa');
INSERT INTO paises (nombre, codigo_iso, capital, poblacion, superficie_km2, moneda, idioma_principal, continente)
VALUES ('Japón', 'JPN', 'Tokio', 125000000, 377975, 'Yen (JPY)', 'Japonés', 'Asia');
INSERT INTO paises (nombre, codigo_iso, capital, poblacion, superficie_km2, moneda, idioma_principal, continente)
VALUES ('Brasil', 'BRA', 'Brasilia', 214000000, 8515767, 'Real (BRL)', 'Portugués', 'América');
INSERT INTO paises (nombre, codigo_iso, capital, poblacion, superficie_km2, moneda, idioma_principal, continente)
VALUES ('Australia', 'AUS', 'Canberra', 26000000, 7692024, 'Dólar australiano (AUD)', 'Inglés', 'Oceanía');


